version: "3"

services: 
  infracloud:
    environment:
      - CSVSERVER_BORDER=Orange
    image: infracloudio/csvserver:latest
    ports: 
      - "9393:9300"
    volumes: 
      - "/root/csvserver/solution/inputFile:/csvserver/inputdata"

  

  prometheus:
    image: prom/prometheus:v2.22.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

