version: "3"

services: 
  infracloud:
    environment:
      - CSVSERVER_BORDER=Orange
    image: infracloudio/csvserver:latest
    ports: 
      - "9393:9300"
    volumes: 
      - "/root/csvserver/solution/inputFile:/csvserver/inputdata"



