global:
  scrape_interval: 15s
  scrape_timeout: 15s

rule_files:
  # - "first rules"
  # - "second rules" 

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ["3.110.117.159:9393"]
